/* ML models, their measured metrics, and the benchmarks behind them.
 *
 * The hard rule on this page: a model's STATUS and the BASIS for its status
 * are different facts and are never merged. `/api/models/hindcast` reports a
 * `selection_basis` precisely because "physics won a benchmark" and "physics
 * is the default because the ML candidate was never measured" would otherwise
 * render identically -- and rendering them identically claims a comparison
 * nobody ran. The page prints the basis in the server's own words.
 *
 * Metrics come from `/api/metrics`, which is regenerated by `ml.evaluate` and
 * the scenario benchmark. Nothing here is entered by hand, and every caveat
 * the API attaches is rendered as prominently as the number it qualifies.
 */

import { useState } from "react";
import {
  AlertTriangle, BrainCircuit, Crosshair, FlaskConical, Info, RefreshCw, Scale,
  ShieldQuestion, Waves,
} from "lucide-react";
import {
  Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, PolarAngleAxis, PolarGrid,
  Radar as RRadar, RadarChart, ResponsiveContainer, Tooltip, XAxis, YAxis,
} from "recharts";

import {
  Badge, DataState, KV, Notice, PageHeader, Panel, Tabs, Tile, chartTheme, useThemeColors,
} from "../components/ui";
import { api, fmt, useApi } from "../lib/api";

const STATUS_TONE = {
  DEPLOYED: "ok", EXPERIMENTAL: "mock", MISSING: "danger",
  "DISABLED ON EVIDENCE": "warn", TRAINED: "accent", UNTRAINED: "neutral",
};

/* The three cases `selection_basis` distinguishes. Spelling them out here is
 * the whole point of the field. */
const BASIS_COPY = {
  measured: { tone: "ok", label: "MEASURED",
    text: "A benchmark ran and this is its winner." },
  untested_candidate: { tone: "warn", label: "UNTESTED CANDIDATE",
    text: "The ML candidate is trained but no benchmark has been recorded. The primary is a default, NOT a winner." },
  candidate_untrained: { tone: "warn", label: "CANDIDATE UNTRAINED",
    text: "The ML candidate has no trained weights and has never predicted anything, so it has never been compared." },
  no_candidate: { tone: "neutral", label: "NO CANDIDATE",
    text: "No ML candidate is implemented for this stage." },
};

export default function Models() {
  const [tab, setTab] = useState("models");
  const modelsQ = useApi(() => api.models(), []);
  const metricsQ = useApi(() => api.metrics(), []);
  const hindQ = useApi(() => api.hindcastModels(), []);

  return (
    <div className="page" data-testid="models-page">
      <PageHeader icon={<BrainCircuit size={17} />} kicker="System" title="ML Models"
        sub="What is deployed, what was measured, and what has never been measured at all."
        actions={<button className="btn btn-sm"
          onClick={() => { modelsQ.reload(); metricsQ.reload(); hindQ.reload(); }}>
          <RefreshCw size={12} /> Refresh
        </button>} />

      <Tabs value={tab} onChange={setTab} testidPrefix="models-tab" items={[
        { id: "models", label: "Deployed models", icon: <BrainCircuit size={12} /> },
        { id: "metrics", label: "Measured metrics", icon: <Scale size={12} /> },
        { id: "hindcast", label: "Hindcast selection", icon: <Waves size={12} /> },
      ]} />

      <div className="mt-3">
        {tab === "models" && <ModelCards q={modelsQ} />}
        {tab === "metrics" && <Metrics q={metricsQ} />}
        {tab === "hindcast" && <Hindcast q={hindQ} />}
      </div>
    </div>
  );
}

/* -------------------------------------------------------- model cards --- */

function ModelCards({ q }) {
  if (q.loading && !q.data) return <DataState kind="loading" title="Reading the model registry" />;
  if (q.error) return <DataState kind="error" error={q.error} />;
  const models = q.data?.models || [];

  return (
    <div className="stack" style={{ gap: 12 }}>
      <div className="grid grid-2">
        {models.map((m) => (
          <Panel key={m.kind} title={m.kind.replace(/_/g, " ")}
            icon={m.status === "EXPERIMENTAL" ? <ShieldQuestion size={12} /> : <BrainCircuit size={12} />}
            right={<Badge tone={STATUS_TONE[m.status] || "neutral"}>{m.status}</Badge>}
            testid={`model-${m.kind}`}>
            <div style={{ fontSize: "var(--fs-lg)", color: "var(--ink-0)", marginBottom: 6 }}>
              {m.name || m.file || "—"}
            </div>
            {/* "not applied to any run" is a deployment fact and is stated,
                never inferred from a green badge. */}
            {m.applied === false && (
              <Badge tone="ghost">NOT APPLIED TO ANY RUN</Badge>
            )}
            {m.note && <Notice tone={m.status === "EXPERIMENTAL" ? "warn" : "info"} style={{ marginTop: 8 }}>{m.note}</Notice>}
            {m.detail && <div className="tiny dim mt-2" style={{ lineHeight: 1.6 }}>{m.detail}</div>}
            {m.sha256 && (
              <dl className="cat-kv mt-3">
                <dt>file</dt><dd className="mono">{m.file}</dd>
                <dt>sha256</dt><dd className="mono cat-hash">{m.sha256}</dd>
                {m.bytes != null && <><dt>bytes</dt><dd className="mono">{fmt.int(m.bytes)}</dd></>}
                {m.config_fingerprint && (
                  <><dt>config</dt><dd className="mono cat-hash">{m.config_fingerprint}</dd></>
                )}
              </dl>
            )}
          </Panel>
        ))}
      </div>
      {q.data?.note && <Notice icon={<Info size={12} />}>{q.data.note}</Notice>}

      {q.data?.recent_runs?.length > 0 && (
        <Panel title="Models used by recent runs" icon={<FlaskConical size={12} />} flush>
          <div className="table-wrap">
            <table>
              <thead><tr><th>Run</th><th>Models</th><th>Code</th></tr></thead>
              <tbody>
                {q.data.recent_runs.map((r) => (
                  <tr key={r.run_id}>
                    <td className="mono tiny">{r.run_id}</td>
                    <td className="tiny">{(r.models || []).map((m) => `${m.kind}: ${m.name}`).join(" · ") || "—"}</td>
                    <td className="mono tiny dim">{String(r.code_git_sha || "").slice(0, 10)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Panel>
      )}
    </div>
  );
}

/* ------------------------------------------------------------ metrics --- */

function Metrics({ q }) {
  const tc = useThemeColors();
  const ct = chartTheme(tc);
  if (q.loading && !q.data) return <DataState kind="loading" title="Reading measured metrics" />;
  if (q.error) return <DataState kind="error" error={q.error} />;

  const d = q.data || {};
  const seg = d.segmentation;
  const screen = d.screening;
  const attr = d.attribution;

  if (!seg && !screen && !attr) {
    return <DataState kind="not-deployed" title="No metrics recorded"
      hint="Metrics are produced by ml.evaluate and the scenario benchmark. Nothing has been evaluated on this deployment." />;
  }

  const tierData = Object.entries(attr?.by_tier || {})
    .map(([tier, v]) => ({ tier, top1: v.top1_rate, scenarios: v.scenarios }));
  const behaviourData = Object.entries(attr?.by_behaviour || {})
    .map(([k, v]) => ({ label: k.replace(/_/g, " ").replace("with ", "+").replace("without ", "−"),
                        rate: v.top1_rate }));

  return (
    <div className="stack" style={{ gap: 12 }}>
      {(d.notes || []).map((n, i) => (
        <Notice key={i} tone="warn" icon={<AlertTriangle size={12} />}>{n}</Notice>
      ))}

      <div className="grid grid-4">
        <Tile label="Attribution top-1" value={attr ? fmt.pct(attr.top1_rate, 0) : "—"} tone="ok"
          sub={attr ? `${attr.top1}/${attr.scenarios} scenarios` : "not measured"} />
        <Tile label="Attribution top-3" value={attr ? fmt.pct(attr.top3_rate, 0) : "—"} tone="ok"
          sub={attr ? `${attr.top3}/${attr.scenarios} scenarios` : "not measured"} />
        <Tile label="Segmentation IoU · oil" value={seg ? fmt.num(seg.oil_tile_iou, 4) : "—"}
          sub={seg ? `${fmt.int(seg.test_tiles)} test tiles` : "not measured"} />
        <Tile label="Look-alike false positives"
          value={screen ? fmt.pct(screen.background_fp_rate, 1) : "—"}
          tone={screen && screen.background_fp_rate < 0.1 ? "ok" : "warn"}
          sub={screen ? `${screen.background_false_positives}/${screen.background_images} patches` : "not measured"} />
      </div>

      {attr && (
        <div className="grid grid-2">
          <Panel title="Attribution by difficulty tier" icon={<Crosshair size={12} />}>
            <div style={{ height: 200 }}>
              <ResponsiveContainer>
                <BarChart data={tierData} margin={{ top: 6, right: 8, left: -22, bottom: 4 }}>
                  <CartesianGrid {...ct.grid} />
                  <XAxis dataKey="tier" tick={ct.axis} axisLine={{ stroke: tc.line }} tickLine={false} />
                  <YAxis tick={ct.axis} axisLine={false} tickLine={false} domain={[0, 1]}
                    tickFormatter={(v) => `${v * 100}%`} />
                  <Tooltip {...ct.tooltip} formatter={(v, n) => [fmt.pct(v, 1), n]} />
                  <Bar dataKey="top1" name="top-1" radius={[2, 2, 0, 0]}>
                    {tierData.map((x, i) => (
                      <Cell key={i} fill={x.top1 > 0.9 ? tc.ok : x.top1 > 0.7 ? tc.warn : tc.danger} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
            <div className="tiny dim mt-2" style={{ lineHeight: 1.55 }}>
              Accuracy falls with difficulty, as it should. Hard scenarios are the ones where the
              culprit leaves little behavioural evidence.
            </div>
          </Panel>

          <Panel title="Accuracy vs available evidence" icon={<Scale size={12} />}>
            <div style={{ height: 200 }}>
              <ResponsiveContainer>
                <RadarChart data={behaviourData} outerRadius="72%">
                  <PolarGrid stroke={tc.line} />
                  <PolarAngleAxis dataKey="label" tick={{ fill: tc.ink2, fontSize: 9 }} />
                  <RRadar dataKey="rate" stroke={tc.accent} fill={tc.accent} fillOpacity={0.26} />
                  <Tooltip {...ct.tooltip} formatter={(v) => [fmt.pct(v, 1), "top-1"]} />
                </RadarChart>
              </ResponsiveContainer>
            </div>
            <div className="tiny dim mt-2" style={{ lineHeight: 1.55 }}>
              The scoring depends on evidence, not luck: a vessel that slows and goes dark is found
              reliably; one that does neither often is not.
            </div>
          </Panel>
        </div>
      )}

      {seg?.sweep?.length > 1 && (
        <Panel title="Detection threshold trade-off" icon={<FlaskConical size={12} />}>
          <div style={{ height: 220 }}>
            <ResponsiveContainer>
              <LineChart data={seg.sweep} margin={{ top: 6, right: 12, left: -22, bottom: 4 }}>
                <CartesianGrid {...ct.grid} />
                <XAxis dataKey="threshold" tick={ct.axis} axisLine={{ stroke: tc.line }} tickLine={false} />
                <YAxis tick={ct.axis} axisLine={false} tickLine={false} domain={[0, 1]} />
                <Tooltip {...ct.tooltip} formatter={(v, n) => [fmt.num(v, 3), n]} />
                <Legend wrapperStyle={{ fontSize: 11 }} />
                <Line type="monotone" dataKey="oil_iou" name="IoU on oil tiles" stroke={tc.oil} strokeWidth={2} dot={{ r: 2 }} />
                <Line type="monotone" dataKey="overall_iou" name="IoU overall" stroke={tc.accent} strokeWidth={2} dot={{ r: 2 }} />
                <Line type="monotone" dataKey="no_oil_firing_rate" name="no-oil tiles firing" stroke={tc.danger} strokeWidth={2} strokeDasharray="4 3" dot={{ r: 2 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </Panel>
      )}

      <div className="grid grid-2">
        {seg && (
          <Panel title="Stage 2 · Segmenter" icon={<BrainCircuit size={12} />}>
            <div className="tiny dim mb-2">{seg.model}</div>
            <div className="kv-dense">
              {seg.checkpoint?.name && <KV k="Deployed checkpoint" v={seg.checkpoint.name} />}
              {seg.checkpoint?.sha256 && (
                <KV k="sha256" v={`${seg.checkpoint.sha256.slice(0, 16)}…`} />
              )}
              <KV k="IoU · oil tiles" v={fmt.num(seg.oil_tile_iou, 4)} tone="ok" />
              <KV k="Precision · oil" v={fmt.num(seg.oil_tile_precision, 3)} />
              <KV k="Recall · oil" v={fmt.num(seg.oil_tile_recall, 3)} />
              <KV k="IoU · whole split" v={fmt.num(seg.overall_iou, 4)} />
              <KV k="No-oil tiles firing"
                v={`${seg.no_oil_firing}/${seg.no_oil_tiles} (${fmt.pct(seg.no_oil_firing_rate, 1)})`} />
              <KV k="dB range" v={seg.db_range ? `${seg.db_range[0]} … ${seg.db_range[1]} dB` : "—"} />
              <KV k="Test split" v={`${seg.scenes ?? "—"} scenes · ${fmt.int(seg.test_tiles)} tiles`} />
              <KV k="Config fingerprint" v={seg.config_fingerprint || "—"} />
            </div>
            {seg.poc_holdout && (
              <Notice tone="warn" style={{ marginTop: 10 }}>
                POC holdout — carved out of Part III itself, so this split is not untouched. Treat
                these as provisional figures.
              </Notice>
            )}
            {seg.pixel_accuracy_note && <Notice style={{ marginTop: 8 }}>{seg.pixel_accuracy_note}</Notice>}
          </Panel>
        )}
        {screen && (
          <Panel title="Stage 1 · Screening detector" icon={<BrainCircuit size={12} />}>
            <div className="tiny dim mb-2">{screen.model}</div>
            <div className="kv-dense">
              <KV k="mAP@0.5" v={fmt.num(screen.map50, 3)} tone="ok" />
              <KV k="mAP@0.5:0.95" v={fmt.num(screen.map50_95, 3)} />
              <KV k="Precision" v={fmt.num(screen.precision, 3)} />
              <KV k="Recall" v={fmt.num(screen.recall, 3)} />
              <KV k="Background FP rate"
                v={`${screen.background_false_positives}/${screen.background_images} (${fmt.pct(screen.background_fp_rate, 1)})`} />
            </div>
            {screen.note && <Notice style={{ marginTop: 10 }}>{screen.note}</Notice>}
          </Panel>
        )}
      </div>

      <Panel title="What these numbers do and do not say" icon={<Info size={12} />}>
        {attr?.note && <Notice style={{ marginBottom: 8 }}>{attr.note}</Notice>}
        {d.drift?.note && <Notice icon={<Waves size={12} />} style={{ marginBottom: 8 }}>{d.drift.note}</Notice>}
        {d.drift?.status && (
          <div className="tiny" data-testid="drift-ml-status">
            <Badge tone="mock">{String(d.drift.status).toUpperCase()}</Badge>{" "}
            <span className="mono">drift ML residual</span>
            {" · "}applied: <span className="mono">{String(d.drift.applied)}</span>
            {" · "}evaluated: <span className="mono">{d.drift.evaluated}</span>
            {d.drift.ml_note && <div className="dim mt-1">{d.drift.ml_note}</div>}
          </div>
        )}
        <div className="tiny dim mt-2">
          Metrics are regenerated by <span className="mono">ml.evaluate</span> and the scenario
          benchmark; nothing on this page is entered by hand.
        </div>
      </Panel>
    </div>
  );
}

/* ----------------------------------------------------------- hindcast --- */

function Hindcast({ q }) {
  if (q.loading && !q.data) return <DataState kind="loading" title="Reading the hindcast benchmark" />;
  if (q.error) return <DataState kind="error" error={q.error} />;
  const d = q.data || {};
  const basis = BASIS_COPY[d.selection_basis] || BASIS_COPY.no_candidate;

  return (
    <div className="stack" style={{ gap: 12 }}>
      {/* The field a demo is most tempted to render as a victory. */}
      <Panel title="Selection basis" icon={<Scale size={12} />}
        right={<Badge tone={basis.tone} lg>{basis.label}</Badge>}>
        <div className="grid grid-3 mb-3">
          <Tile label="Primary" value={d.primary || "—"} tone="accent" />
          <Tile label="Fallback" value={d.fallback || "none"} />
          <Tile label="Benchmark run" value={d.benchmark_run ? "YES" : "NO"}
            tone={d.benchmark_run ? "ok" : "warn"} />
        </div>
        <Notice tone={d.benchmark_run ? "info" : "warn"}>
          <strong>{basis.text}</strong>
          {d.selection_detail && <> {d.selection_detail}</>}
        </Notice>
      </Panel>

      <Panel title="Candidates" icon={<FlaskConical size={12} />} flush>
        <div className="table-wrap">
          <table>
            <thead>
              <tr><th>Candidate</th><th>Status</th><th>Applied</th><th>Detail</th></tr>
            </thead>
            <tbody>
              {(d.candidates || []).map((c) => (
                <tr key={c.candidate}>
                  <td>
                    <div className="strong">{c.name}</div>
                    <div className="sub mono">{c.candidate}</div>
                  </td>
                  <td><Badge tone={STATUS_TONE[c.status] || "neutral"}>{c.status}</Badge></td>
                  <td>
                    {c.applied_to_runs
                      ? <Badge tone="ok">YES</Badge>
                      : <Badge tone="ghost">NO</Badge>}
                  </td>
                  <td className="tiny dim" style={{ maxWidth: 420, whiteSpace: "normal" }}>
                    {c.note || c.formulation || "—"}
                    {c.measured && (
                      <div className="mono mt-1">
                        {Object.entries(c.measured).slice(0, 4)
                          .map(([k, v]) => `${k}: ${typeof v === "number" ? v.toFixed(2) : v}`).join(" · ")}
                      </div>
                    )}
                    {c.weights_present === false && (
                      <div className="tone-warn mt-1">no trained weights in this checkout</div>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Panel>

      <Notice icon={<Info size={12} />}>
        The origin estimate every sealed run carries is physics — a Lagrangian backward
        integration. Whether machine learning could beat it is a separate question, and this page
        answers it only when a benchmark has actually been run.
      </Notice>
    </div>
  );
}
